comment: false
codecov:
       token: a194d065-e132-4173-b437-45fd9eb6ef49
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
      enabled: false
