name: Test-Package

on:
  push:         {branches: [main, dev]}
  pull_request: {branches: [main, dev]}



jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
          python-version: ${{ matrix.python-version }}


    - name: Install package dependencies
      run: |
       python -m pip install --upgrade pip setuptools wheel
       pip install -r requirements.txt

    - name: Install package
      run: python3 setup.py install

    - name: Upload reports to codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: |
       coverage run tests.py && coverage report -m && coverage xml 
       curl -Os https://uploader.codecov.io/latest/linux/codecov
       chmod +x codecov
       ./codecov -t ${CODECOV_TOKEN} -R /home/runner/work/pycite -f "coverage.xml"

    - name: Test Script Mode
      run: touch testfiles/citations.txt && python -m pycite -i testfiles/testlinks.txt -o testfiles/citations.txt
    - name: Check that logging works 
      run: if [ -f pycite_log.log ]; then cat pycite_log.log && rm pycite_log.log;fi;

